<?php

return [

    'View'       	 => System\Codememory\AbstractComponent\View::class,
    'Random'     	 => System\Support\Random::class,
    'Cookie'     	 => System\Support\Cookie::class,
    'Date'       	 => System\Support\Date::class,
    'Session'    	 => System\Support\Session\Session::class,
    'Request'    	 => \System\Http\Request::class,
    'Common'     	 => System\Support\Common::class,
    'Env'        	 => System\ENV\AppEnv::class,
    'Validator'  	 => System\Validator\Validate\Validator::class,
    'File'        	 => System\Inc\File::class,
    'Ini'        	 => System\Inc\FileIni::class,
    'Fopen'      	 => System\Inc\FopenFile::class,
    'Db'         	 => System\Database\DatabaseSingleton::class,
    'Assets'     	 => System\Codememory\Components\Assets\Assets::class,
    'Build'     	 => System\Codememory\Components\Assets\Build::class,
    'Cache'      	 => System\Classes\Cache\Cache::class,
    'Customize'  	 => System\Customize\MainCustomize::class,
    'Router'     	 => System\Router\Router::class,
    'Theme'      	 => System\Codememory\AbstractComponent\Theme::class,
    'Response'   	 => System\Http\Response::class,
    'Access'     	 => System\Http\Access\Handle::class,
    'Translete'  	 => System\Languages\Translate::class,
    'Redirector' 	 => System\Http\Header\Redirect::class,
    'Header'     	 => System\Http\Header\Header::class,
    'Store'      	 => System\Codememory\Console\Store::class,
    'Request'    	 => System\Http\NewRequest::class,
    'Server'     	 => System\Http\Server::class,
    'Auth'       	 => System\Authentication\Authorization::class,
    'Register'       => System\Authentication\Registration::class,
    'Plugin'       	 => System\Plugins\PluginHandle::class,
    'Config'       	 => System\Codememory\Components\Config\ConfigManager::class,
    'Model'       	 => System\Codememory\AbstractComponent\Model\Handle::class,
    'Url'       	 => System\Http\Url::class,
	'CompilerCM'	 => System\Codememory\CodememoryConfigurationLanguage\ReinforcerCodememory::class,
	'Yml'	 		 => System\Inc\FileYaml::class,
	'Flash'	 		 => System\Support\Session\Flash::class,
	'Lang'	 		 => System\Languages\Language\Language::class,
    
];