<?php

return [
    
    'Session'    	 => System\Classes\Facade\Facades\SessionFacade::class,
    'Cookie'     	 => System\Classes\Facade\Facades\CookieFacade::class,
    'Assets'     	 => System\Classes\Facade\Facades\AssetsFacade::class,
    'Build'     	 => System\Classes\Facade\Facades\BuildFacade::class,
    'Common'     	 => System\Classes\Facade\Facades\CommonFacade::class,
    'Date'       	 => System\Classes\Facade\Facades\DateFacade::class,
    'Random'     	 => System\Classes\Facade\Facades\RandomFacade::class,
    'View'       	 => System\Classes\Facade\Facades\ViewFacade::class,
    'Env'        	 => System\Classes\Facade\Facades\EnvFacade::class,
    'Cache'      	 => System\Classes\Facade\Facades\CacheFacade::class,
    'Fopen'      	 => System\Classes\Facade\Facades\FopenFacade::class,
    'Validator'  	 => System\Classes\Facade\Facades\ValidatorFacade::class,
    'Customize'  	 => System\Classes\Facade\Facades\CustomizeFacade::class,
    'Router'     	 => System\Classes\Facade\Facades\RouterFacade::class,
    'File'        	 => System\Classes\Facade\Facades\FileFacade::class,
    'Theme'      	 => System\Classes\Facade\Facades\ThemeFacade::class,
    'Db'         	 => System\Classes\Facade\Facades\DbFacade::class,
    'Response'   	 => System\Classes\Facade\Facades\ResponseFacade::class,
    'Access'     	 => System\Classes\Facade\Facades\AccessHandleFacade::class,
    'Translete'  	 => System\Classes\Facade\Facades\TransleteFacade::class,
    'Redirector' 	 => System\Classes\Facade\Facades\RedirectorFacade::class,
    'Header'     	 => System\Classes\Facade\Facades\HeaderFacade::class,
    'Ini'        	 => System\Classes\Facade\Facades\IniFacade::class,
    'Store'      	 => System\Classes\Facade\Facades\StoreFacade::class,
    'Request'    	 => System\Classes\Facade\Facades\RequestFacade::class,
    'Server'     	 => System\Classes\Facade\Facades\ServerFacade::class,
    'Auth'       	 => System\Classes\Facade\Facades\AuthFacade::class,
    'Register'       => System\Classes\Facade\Facades\RegisterFacade::class,
    'Plugin'       	 => System\Classes\Facade\Facades\PluginFacade::class,
    'Config'       	 => System\Classes\Facade\Facades\ConfigFacade::class,
    'Model'       	 => System\Classes\Facade\Facades\ModelFacade::class,
    'Url'       	 => System\Classes\Facade\Facades\UrlFacade::class,
	'CompilerCM'     => System\Classes\Facade\Facades\CompilerCM::class,
    'Yml'     		 => System\Classes\Facade\Facades\YmlFacade::class,
    'Flash'          => System\Classes\Facade\Facades\FlashFacade::class,
    'Lang'           => System\Classes\Facade\Facades\LangFacade::class

];